# Generated by Django 4.2 on 2023-04-25 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plataforma", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Imagem", new_name="Imagen",),
        migrations.RenameModel(old_name="Imovel", new_name="Imovei",),
        migrations.RenameModel(old_name="Visitas", new_name="Visita",),
    ]
