# Generated by Django 4.2 on 2023-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma", "0002_rename_imagem_imagen_rename_imovel_imovei_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visita", name="horario", field=models.CharField(max_length=24),
        ),
    ]
